name = "RapunSL"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["RapunSL"]

[leanOptions]
pp.unicode.fun = true                 # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[require]]
name = "iris"
git.url = "https://github.com/leanprover-community/iris-lean.git"
git.subDir = "Iris"
rev = "48afae08e80d33c2ebe4374b9701c832f8e8f28e"

[[lean_lib]]
name = "RapunSL"
